### ISSUE TITLE
Contact us page

### ISSUE THREAD

**Issue by jchiam** [jchiam/accorde-site#32]
- [x] Add group photo
~Add background design thingy~
- [x]  Add facebook and youtube icon buttons

**Comment by jchiam** [comment]
@shira9298 I don't think i have the assets for the background three circles thingy you created during the last meeting.

**Comment by shira9298** [comment]
where did I share all the svg files last time ah?

**Comment by jchiam** [comment]
supposed to be on google drive. i only found the chevron. no three circles

**Comment by shira9298** [comment]
i thought i created alot of svg for youtube logo etc using github :( all gone
